/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Sun Sep 10 15:08:14 2023. */

#include "notehub-udp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t notelib_NotehubUdpPB_fields[2] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, notelib_NotehubUdpPB, Payload, Payload, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
