// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notehub.proto

/*
Package notelib is a generated protocol buffer package.

Package notelib notehub.proto are the protocol definitions for notebox-notehub comms

It is generated from these files:
	notehub.proto

It has these top-level messages:
	NotehubPB
*/
package notelib

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotehubPB struct {
	Version                        *int64  `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
	MessageType                    *string `protobuf:"bytes,2,opt,name=MessageType" json:"MessageType,omitempty"`
	Error                          *string `protobuf:"bytes,3,opt,name=Error" json:"Error,omitempty"`
	DeviceUID                      *string `protobuf:"bytes,4,opt,name=DeviceUID" json:"DeviceUID,omitempty"`
	DeviceEndpointID               *string `protobuf:"bytes,5,opt,name=DeviceEndpointID" json:"DeviceEndpointID,omitempty"`
	HubTimeNs                      *int64  `protobuf:"varint,6,opt,name=HubTimeNs" json:"HubTimeNs,omitempty"`
	HubEndpointID                  *string `protobuf:"bytes,7,opt,name=HubEndpointID" json:"HubEndpointID,omitempty"`
	HubSessionTicket               *string `protobuf:"bytes,8,opt,name=HubSessionTicket" json:"HubSessionTicket,omitempty"`
	HubSessionHandler              *string `protobuf:"bytes,9,opt,name=HubSessionHandler" json:"HubSessionHandler,omitempty"`
	HubSessionTicketExpiresTimeSec *int64  `protobuf:"varint,10,opt,name=HubSessionTicketExpiresTimeSec" json:"HubSessionTicketExpiresTimeSec,omitempty"`
	NotefileID                     *string `protobuf:"bytes,11,opt,name=NotefileID" json:"NotefileID,omitempty"`
	NotefileIDs                    *string `protobuf:"bytes,12,opt,name=NotefileIDs" json:"NotefileIDs,omitempty"`
	Since                          *int64  `protobuf:"varint,13,opt,name=Since" json:"Since,omitempty"`
	Until                          *int64  `protobuf:"varint,14,opt,name=Until" json:"Until,omitempty"`
	MaxChanges                     *int64  `protobuf:"varint,15,opt,name=MaxChanges" json:"MaxChanges,omitempty"`
	DeviceSN                       *string `protobuf:"bytes,16,opt,name=DeviceSN" json:"DeviceSN,omitempty"`
	NoteID                         *string `protobuf:"bytes,17,opt,name=NoteID" json:"NoteID,omitempty"`
	SessionIDPrev                  *int64  `protobuf:"varint,18,opt,name=SessionIDPrev" json:"SessionIDPrev,omitempty"`
	SessionIDNext                  *int64  `protobuf:"varint,19,opt,name=SessionIDNext" json:"SessionIDNext,omitempty"`
	SessionIDMismatch              *bool   `protobuf:"varint,20,opt,name=SessionIDMismatch" json:"SessionIDMismatch,omitempty"`
	Bytes1                         *int64  `protobuf:"varint,21,opt,name=Bytes1" json:"Bytes1,omitempty"`
	Bytes2                         *int64  `protobuf:"varint,22,opt,name=Bytes2" json:"Bytes2,omitempty"`
	Bytes3                         *int64  `protobuf:"varint,23,opt,name=Bytes3" json:"Bytes3,omitempty"`
	Bytes4                         *int64  `protobuf:"varint,24,opt,name=Bytes4" json:"Bytes4,omitempty"`
	ProductUID                     *string `protobuf:"bytes,25,opt,name=ProductUID" json:"ProductUID,omitempty"`
	UsageProvisioned               *int64  `protobuf:"varint,26,opt,name=UsageProvisioned" json:"UsageProvisioned,omitempty"`
	UsageRcvdBytes                 *uint32 `protobuf:"varint,27,opt,name=UsageRcvdBytes" json:"UsageRcvdBytes,omitempty"`
	UsageSentBytes                 *uint32 `protobuf:"varint,28,opt,name=UsageSentBytes" json:"UsageSentBytes,omitempty"`
	UsageTCPSessions               *uint32 `protobuf:"varint,29,opt,name=UsageTCPSessions" json:"UsageTCPSessions,omitempty"`
	UsageTLSSessions               *uint32 `protobuf:"varint,30,opt,name=UsageTLSSessions" json:"UsageTLSSessions,omitempty"`
	UsageRcvdNotes                 *uint32 `protobuf:"varint,31,opt,name=UsageRcvdNotes" json:"UsageRcvdNotes,omitempty"`
	UsageSentNotes                 *uint32 `protobuf:"varint,32,opt,name=UsageSentNotes" json:"UsageSentNotes,omitempty"`
	CellID                         *string `protobuf:"bytes,33,opt,name=CellID" json:"CellID,omitempty"`
	NotificationSession            *bool   `protobuf:"varint,34,opt,name=NotificationSession" json:"NotificationSession,omitempty"`
	Voltage100                     *int32  `protobuf:"varint,35,opt,name=Voltage100" json:"Voltage100,omitempty"`
	Temp100                        *int32  `protobuf:"varint,36,opt,name=Temp100" json:"Temp100,omitempty"`
	Development                    *bool   `protobuf:"varint,37,opt,name=Development" json:"Development,omitempty"`
	XXX_unrecognized               []byte  `json:"-"`
}

func (m *NotehubPB) Reset()                    { *m = NotehubPB{} }
func (m *NotehubPB) String() string            { return proto.CompactTextString(m) }
func (*NotehubPB) ProtoMessage()               {}
func (*NotehubPB) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NotehubPB) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *NotehubPB) GetMessageType() string {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return ""
}

func (m *NotehubPB) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *NotehubPB) GetDeviceUID() string {
	if m != nil && m.DeviceUID != nil {
		return *m.DeviceUID
	}
	return ""
}

func (m *NotehubPB) GetDeviceEndpointID() string {
	if m != nil && m.DeviceEndpointID != nil {
		return *m.DeviceEndpointID
	}
	return ""
}

func (m *NotehubPB) GetHubTimeNs() int64 {
	if m != nil && m.HubTimeNs != nil {
		return *m.HubTimeNs
	}
	return 0
}

func (m *NotehubPB) GetHubEndpointID() string {
	if m != nil && m.HubEndpointID != nil {
		return *m.HubEndpointID
	}
	return ""
}

func (m *NotehubPB) GetHubSessionTicket() string {
	if m != nil && m.HubSessionTicket != nil {
		return *m.HubSessionTicket
	}
	return ""
}

func (m *NotehubPB) GetHubSessionHandler() string {
	if m != nil && m.HubSessionHandler != nil {
		return *m.HubSessionHandler
	}
	return ""
}

func (m *NotehubPB) GetHubSessionTicketExpiresTimeSec() int64 {
	if m != nil && m.HubSessionTicketExpiresTimeSec != nil {
		return *m.HubSessionTicketExpiresTimeSec
	}
	return 0
}

func (m *NotehubPB) GetNotefileID() string {
	if m != nil && m.NotefileID != nil {
		return *m.NotefileID
	}
	return ""
}

func (m *NotehubPB) GetNotefileIDs() string {
	if m != nil && m.NotefileIDs != nil {
		return *m.NotefileIDs
	}
	return ""
}

func (m *NotehubPB) GetSince() int64 {
	if m != nil && m.Since != nil {
		return *m.Since
	}
	return 0
}

func (m *NotehubPB) GetUntil() int64 {
	if m != nil && m.Until != nil {
		return *m.Until
	}
	return 0
}

func (m *NotehubPB) GetMaxChanges() int64 {
	if m != nil && m.MaxChanges != nil {
		return *m.MaxChanges
	}
	return 0
}

func (m *NotehubPB) GetDeviceSN() string {
	if m != nil && m.DeviceSN != nil {
		return *m.DeviceSN
	}
	return ""
}

func (m *NotehubPB) GetNoteID() string {
	if m != nil && m.NoteID != nil {
		return *m.NoteID
	}
	return ""
}

func (m *NotehubPB) GetSessionIDPrev() int64 {
	if m != nil && m.SessionIDPrev != nil {
		return *m.SessionIDPrev
	}
	return 0
}

func (m *NotehubPB) GetSessionIDNext() int64 {
	if m != nil && m.SessionIDNext != nil {
		return *m.SessionIDNext
	}
	return 0
}

func (m *NotehubPB) GetSessionIDMismatch() bool {
	if m != nil && m.SessionIDMismatch != nil {
		return *m.SessionIDMismatch
	}
	return false
}

func (m *NotehubPB) GetBytes1() int64 {
	if m != nil && m.Bytes1 != nil {
		return *m.Bytes1
	}
	return 0
}

func (m *NotehubPB) GetBytes2() int64 {
	if m != nil && m.Bytes2 != nil {
		return *m.Bytes2
	}
	return 0
}

func (m *NotehubPB) GetBytes3() int64 {
	if m != nil && m.Bytes3 != nil {
		return *m.Bytes3
	}
	return 0
}

func (m *NotehubPB) GetBytes4() int64 {
	if m != nil && m.Bytes4 != nil {
		return *m.Bytes4
	}
	return 0
}

func (m *NotehubPB) GetProductUID() string {
	if m != nil && m.ProductUID != nil {
		return *m.ProductUID
	}
	return ""
}

func (m *NotehubPB) GetUsageProvisioned() int64 {
	if m != nil && m.UsageProvisioned != nil {
		return *m.UsageProvisioned
	}
	return 0
}

func (m *NotehubPB) GetUsageRcvdBytes() uint32 {
	if m != nil && m.UsageRcvdBytes != nil {
		return *m.UsageRcvdBytes
	}
	return 0
}

func (m *NotehubPB) GetUsageSentBytes() uint32 {
	if m != nil && m.UsageSentBytes != nil {
		return *m.UsageSentBytes
	}
	return 0
}

func (m *NotehubPB) GetUsageTCPSessions() uint32 {
	if m != nil && m.UsageTCPSessions != nil {
		return *m.UsageTCPSessions
	}
	return 0
}

func (m *NotehubPB) GetUsageTLSSessions() uint32 {
	if m != nil && m.UsageTLSSessions != nil {
		return *m.UsageTLSSessions
	}
	return 0
}

func (m *NotehubPB) GetUsageRcvdNotes() uint32 {
	if m != nil && m.UsageRcvdNotes != nil {
		return *m.UsageRcvdNotes
	}
	return 0
}

func (m *NotehubPB) GetUsageSentNotes() uint32 {
	if m != nil && m.UsageSentNotes != nil {
		return *m.UsageSentNotes
	}
	return 0
}

func (m *NotehubPB) GetCellID() string {
	if m != nil && m.CellID != nil {
		return *m.CellID
	}
	return ""
}

func (m *NotehubPB) GetNotificationSession() bool {
	if m != nil && m.NotificationSession != nil {
		return *m.NotificationSession
	}
	return false
}

func (m *NotehubPB) GetVoltage100() int32 {
	if m != nil && m.Voltage100 != nil {
		return *m.Voltage100
	}
	return 0
}

func (m *NotehubPB) GetTemp100() int32 {
	if m != nil && m.Temp100 != nil {
		return *m.Temp100
	}
	return 0
}

func (m *NotehubPB) GetDevelopment() bool {
	if m != nil && m.Development != nil {
		return *m.Development
	}
	return false
}

func init() {
	proto.RegisterType((*NotehubPB)(nil), "notelib.NotehubPB")
}

func init() { proto.RegisterFile("notehub.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xdd, 0x4e, 0xdb, 0x40,
	0x10, 0x85, 0xe5, 0x52, 0x7e, 0xb2, 0x34, 0x14, 0x16, 0x4a, 0xa7, 0x94, 0x52, 0x97, 0xd2, 0x2a,
	0xaa, 0xaa, 0x8a, 0xbf, 0x27, 0x00, 0x53, 0xc5, 0x52, 0x89, 0x22, 0x3b, 0x70, 0xef, 0x38, 0x03,
	0xac, 0xea, 0x78, 0x2d, 0xef, 0x26, 0x82, 0xe7, 0xe8, 0x0b, 0x57, 0xb3, 0x1b, 0xec, 0x8d, 0x53,
	0xa9, 0x97, 0xe7, 0x9b, 0xa3, 0x39, 0x13, 0x1f, 0x3b, 0xac, 0x9d, 0x4b, 0x8d, 0x0f, 0x93, 0xe1,
	0x8f, 0xa2, 0x94, 0x5a, 0xf2, 0x55, 0x92, 0x99, 0x18, 0x1e, 0xfe, 0x61, 0xac, 0xd5, 0xb3, 0xa3,
	0xfe, 0x05, 0x07, 0xb6, 0x7a, 0x8b, 0xa5, 0x12, 0x32, 0x07, 0xcf, 0xf7, 0x3a, 0x4b, 0xd1, 0xb3,
	0xe4, 0x3e, 0x5b, 0xbf, 0x46, 0xa5, 0x92, 0x7b, 0x1c, 0x3c, 0x15, 0x08, 0x2f, 0x7c, 0xaf, 0xd3,
	0x8a, 0x5c, 0xc4, 0x77, 0xd8, 0xf2, 0x55, 0x59, 0xca, 0x12, 0x96, 0xcc, 0xcc, 0x0a, 0xbe, 0xcf,
	0x5a, 0x01, 0x4e, 0x45, 0x8a, 0x37, 0x61, 0x00, 0x2f, 0xcd, 0xa4, 0x06, 0xfc, 0x1b, 0xdb, 0xb4,
	0xe2, 0x2a, 0x1f, 0x15, 0x52, 0xe4, 0x3a, 0x0c, 0x60, 0xd9, 0x98, 0x16, 0x38, 0x6d, 0xea, 0x4e,
	0x86, 0x03, 0x31, 0xc6, 0x9e, 0x82, 0x15, 0x73, 0x5d, 0x0d, 0xf8, 0x11, 0x6b, 0x77, 0x27, 0x43,
	0x67, 0xcd, 0xaa, 0x59, 0x33, 0x0f, 0x29, 0xaf, 0x3b, 0x19, 0xc6, 0xa8, 0xe8, 0x37, 0x0d, 0x44,
	0xfa, 0x1b, 0x35, 0xac, 0xd9, 0xbc, 0x26, 0xe7, 0xdf, 0xd9, 0x56, 0xcd, 0xba, 0x49, 0x3e, 0xca,
	0xb0, 0x84, 0x96, 0x31, 0x2f, 0x0e, 0xf8, 0x4f, 0x76, 0xd0, 0xdc, 0x70, 0xf5, 0x58, 0x88, 0x12,
	0x15, 0x1d, 0x18, 0x63, 0x0a, 0xcc, 0x9c, 0xfc, 0x1f, 0x17, 0x3f, 0x60, 0x8c, 0xea, 0xb8, 0x13,
	0x19, 0x86, 0x01, 0xac, 0x9b, 0x38, 0x87, 0x50, 0x0f, 0xb5, 0x52, 0xf0, 0xca, 0xf6, 0xe0, 0x20,
	0xea, 0x21, 0x16, 0x79, 0x8a, 0xd0, 0x36, 0x81, 0x56, 0x10, 0xbd, 0xc9, 0xb5, 0xc8, 0x60, 0xc3,
	0x52, 0x23, 0x28, 0xed, 0x3a, 0x79, 0xbc, 0x7c, 0x48, 0xf2, 0x7b, 0x54, 0xf0, 0xda, 0x8c, 0x1c,
	0xc2, 0xf7, 0xd8, 0x9a, 0xed, 0x21, 0xee, 0xc1, 0xa6, 0x89, 0xaa, 0x34, 0xdf, 0x65, 0x2b, 0x14,
	0x1b, 0x06, 0xb0, 0x65, 0x26, 0x33, 0x45, 0x4d, 0xcc, 0x7e, 0x60, 0x18, 0xf4, 0x4b, 0x9c, 0x02,
	0x37, 0x6b, 0xe7, 0xe1, 0x9c, 0xab, 0x87, 0x8f, 0x1a, 0xb6, 0x1b, 0x2e, 0x82, 0xd4, 0x41, 0x05,
	0xae, 0x85, 0x1a, 0x27, 0x3a, 0x7d, 0x80, 0x1d, 0xdf, 0xeb, 0xac, 0x45, 0x8b, 0x03, 0xba, 0xe8,
	0xe2, 0x49, 0xa3, 0x3a, 0x81, 0x37, 0x66, 0xd9, 0x4c, 0x55, 0xfc, 0x14, 0x76, 0x1d, 0x7e, 0x5a,
	0xf1, 0x33, 0x78, 0xeb, 0xf0, 0xb3, 0x8a, 0x9f, 0x03, 0x38, 0xfc, 0x9c, 0x9e, 0x56, 0xbf, 0x94,
	0xa3, 0x49, 0xaa, 0xe9, 0x65, 0x7e, 0x67, 0xbb, 0xa9, 0x09, 0xbd, 0x5d, 0x37, 0xf4, 0x39, 0xf4,
	0x4b, 0x39, 0x15, 0x74, 0x1b, 0x8e, 0x60, 0xcf, 0x6c, 0x58, 0xe0, 0xfc, 0x2b, 0xdb, 0x30, 0x2c,
	0x4a, 0xa7, 0x23, 0xb3, 0x1e, 0xde, 0xfb, 0x5e, 0xa7, 0x1d, 0x35, 0x68, 0xe5, 0x8b, 0x31, 0xd7,
	0xd6, 0xb7, 0xef, 0xf8, 0x2a, 0x5a, 0x65, 0x0f, 0x2e, 0xfb, 0xb3, 0x07, 0xa3, 0xe0, 0x83, 0x71,
	0x2e, 0xf0, 0xda, 0xfb, 0x2b, 0xae, 0xbc, 0x07, 0xae, 0xb7, 0xe6, 0x73, 0x77, 0x52, 0xc1, 0x0a,
	0x3e, 0x36, 0xee, 0x34, 0x74, 0xee, 0x4e, 0xeb, 0xf3, 0x1b, 0x77, 0x5a, 0xdf, 0x2e, 0x5b, 0xb9,
	0xc4, 0x2c, 0x0b, 0x03, 0xf8, 0x64, 0xdf, 0x1a, 0xab, 0xf8, 0x31, 0xdb, 0xee, 0x49, 0x2d, 0xee,
	0x44, 0x9a, 0x68, 0x21, 0xf3, 0x59, 0x3e, 0x1c, 0x9a, 0xae, 0xff, 0x35, 0xa2, 0x36, 0x6e, 0x65,
	0xa6, 0x93, 0x7b, 0x3c, 0x39, 0x3e, 0x86, 0xcf, 0xbe, 0xd7, 0x59, 0x8e, 0x1c, 0x42, 0xff, 0x65,
	0x03, 0x1c, 0x17, 0x34, 0x3c, 0x32, 0xc3, 0x67, 0x49, 0xdf, 0x50, 0x80, 0x53, 0xcc, 0x64, 0x31,
	0xc6, 0x5c, 0xc3, 0x17, 0x93, 0xe1, 0xa2, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x99, 0x2e, 0x5d,
	0x4f, 0x2e, 0x05, 0x00, 0x00,
}
