// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notehub.proto

/*
Package notelib is a generated protocol buffer package.

Package notelib notehub.proto are the protocol definitions for notebox-notehub comms

It is generated from these files:
	notehub.proto

It has these top-level messages:
	NotehubPB
*/
package notelib

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotehubPB struct {
	Version                        *int64  `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
	MessageType                    *string `protobuf:"bytes,2,opt,name=MessageType" json:"MessageType,omitempty"`
	Error                          *string `protobuf:"bytes,3,opt,name=Error" json:"Error,omitempty"`
	DeviceUID                      *string `protobuf:"bytes,4,opt,name=DeviceUID" json:"DeviceUID,omitempty"`
	DeviceEndpointID               *string `protobuf:"bytes,5,opt,name=DeviceEndpointID" json:"DeviceEndpointID,omitempty"`
	HubTimeNs                      *int64  `protobuf:"varint,6,opt,name=HubTimeNs" json:"HubTimeNs,omitempty"`
	HubEndpointID                  *string `protobuf:"bytes,7,opt,name=HubEndpointID" json:"HubEndpointID,omitempty"`
	HubSessionTicket               *string `protobuf:"bytes,8,opt,name=HubSessionTicket" json:"HubSessionTicket,omitempty"`
	HubSessionHandler              *string `protobuf:"bytes,9,opt,name=HubSessionHandler" json:"HubSessionHandler,omitempty"`
	HubSessionTicketExpiresTimeSec *int64  `protobuf:"varint,10,opt,name=HubSessionTicketExpiresTimeSec" json:"HubSessionTicketExpiresTimeSec,omitempty"`
	NotefileID                     *string `protobuf:"bytes,11,opt,name=NotefileID" json:"NotefileID,omitempty"`
	NotefileIDs                    *string `protobuf:"bytes,12,opt,name=NotefileIDs" json:"NotefileIDs,omitempty"`
	Since                          *int64  `protobuf:"varint,13,opt,name=Since" json:"Since,omitempty"`
	Until                          *int64  `protobuf:"varint,14,opt,name=Until" json:"Until,omitempty"`
	MaxChanges                     *int64  `protobuf:"varint,15,opt,name=MaxChanges" json:"MaxChanges,omitempty"`
	DeviceSN                       *string `protobuf:"bytes,16,opt,name=DeviceSN" json:"DeviceSN,omitempty"`
	NoteID                         *string `protobuf:"bytes,17,opt,name=NoteID" json:"NoteID,omitempty"`
	SessionIDPrev                  *int64  `protobuf:"varint,18,opt,name=SessionIDPrev" json:"SessionIDPrev,omitempty"`
	SessionIDNext                  *int64  `protobuf:"varint,19,opt,name=SessionIDNext" json:"SessionIDNext,omitempty"`
	SessionIDMismatch              *bool   `protobuf:"varint,20,opt,name=SessionIDMismatch" json:"SessionIDMismatch,omitempty"`
	Bytes1                         *int64  `protobuf:"varint,21,opt,name=Bytes1" json:"Bytes1,omitempty"`
	Bytes2                         *int64  `protobuf:"varint,22,opt,name=Bytes2" json:"Bytes2,omitempty"`
	Bytes3                         *int64  `protobuf:"varint,23,opt,name=Bytes3" json:"Bytes3,omitempty"`
	Bytes4                         *int64  `protobuf:"varint,24,opt,name=Bytes4" json:"Bytes4,omitempty"`
	ProductUID                     *string `protobuf:"bytes,25,opt,name=ProductUID" json:"ProductUID,omitempty"`
	UsageProvisioned               *int64  `protobuf:"varint,26,opt,name=UsageProvisioned" json:"UsageProvisioned,omitempty"`
	UsageRcvdBytes                 *uint32 `protobuf:"varint,27,opt,name=UsageRcvdBytes" json:"UsageRcvdBytes,omitempty"`
	UsageSentBytes                 *uint32 `protobuf:"varint,28,opt,name=UsageSentBytes" json:"UsageSentBytes,omitempty"`
	UsageTCPSessions               *uint32 `protobuf:"varint,29,opt,name=UsageTCPSessions" json:"UsageTCPSessions,omitempty"`
	UsageTLSSessions               *uint32 `protobuf:"varint,30,opt,name=UsageTLSSessions" json:"UsageTLSSessions,omitempty"`
	UsageRcvdNotes                 *uint32 `protobuf:"varint,31,opt,name=UsageRcvdNotes" json:"UsageRcvdNotes,omitempty"`
	UsageSentNotes                 *uint32 `protobuf:"varint,32,opt,name=UsageSentNotes" json:"UsageSentNotes,omitempty"`
	CellID                         *string `protobuf:"bytes,33,opt,name=CellID" json:"CellID,omitempty"`
	NotificationSession            *bool   `protobuf:"varint,34,opt,name=NotificationSession" json:"NotificationSession,omitempty"`
	Voltage100                     *int32  `protobuf:"varint,35,opt,name=Voltage100" json:"Voltage100,omitempty"`
	Temp100                        *int32  `protobuf:"varint,36,opt,name=Temp100" json:"Temp100,omitempty"`
	ContinuousSession              *bool   `protobuf:"varint,37,opt,name=ContinuousSession" json:"ContinuousSession,omitempty"`
	MotionSecs                     *int64  `protobuf:"varint,38,opt,name=MotionSecs" json:"MotionSecs,omitempty"`
	MotionOrientation              *string `protobuf:"bytes,39,opt,name=MotionOrientation" json:"MotionOrientation,omitempty"`
	XXX_unrecognized               []byte  `json:"-"`
}

func (m *NotehubPB) Reset()                    { *m = NotehubPB{} }
func (m *NotehubPB) String() string            { return proto.CompactTextString(m) }
func (*NotehubPB) ProtoMessage()               {}
func (*NotehubPB) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NotehubPB) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *NotehubPB) GetMessageType() string {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return ""
}

func (m *NotehubPB) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *NotehubPB) GetDeviceUID() string {
	if m != nil && m.DeviceUID != nil {
		return *m.DeviceUID
	}
	return ""
}

func (m *NotehubPB) GetDeviceEndpointID() string {
	if m != nil && m.DeviceEndpointID != nil {
		return *m.DeviceEndpointID
	}
	return ""
}

func (m *NotehubPB) GetHubTimeNs() int64 {
	if m != nil && m.HubTimeNs != nil {
		return *m.HubTimeNs
	}
	return 0
}

func (m *NotehubPB) GetHubEndpointID() string {
	if m != nil && m.HubEndpointID != nil {
		return *m.HubEndpointID
	}
	return ""
}

func (m *NotehubPB) GetHubSessionTicket() string {
	if m != nil && m.HubSessionTicket != nil {
		return *m.HubSessionTicket
	}
	return ""
}

func (m *NotehubPB) GetHubSessionHandler() string {
	if m != nil && m.HubSessionHandler != nil {
		return *m.HubSessionHandler
	}
	return ""
}

func (m *NotehubPB) GetHubSessionTicketExpiresTimeSec() int64 {
	if m != nil && m.HubSessionTicketExpiresTimeSec != nil {
		return *m.HubSessionTicketExpiresTimeSec
	}
	return 0
}

func (m *NotehubPB) GetNotefileID() string {
	if m != nil && m.NotefileID != nil {
		return *m.NotefileID
	}
	return ""
}

func (m *NotehubPB) GetNotefileIDs() string {
	if m != nil && m.NotefileIDs != nil {
		return *m.NotefileIDs
	}
	return ""
}

func (m *NotehubPB) GetSince() int64 {
	if m != nil && m.Since != nil {
		return *m.Since
	}
	return 0
}

func (m *NotehubPB) GetUntil() int64 {
	if m != nil && m.Until != nil {
		return *m.Until
	}
	return 0
}

func (m *NotehubPB) GetMaxChanges() int64 {
	if m != nil && m.MaxChanges != nil {
		return *m.MaxChanges
	}
	return 0
}

func (m *NotehubPB) GetDeviceSN() string {
	if m != nil && m.DeviceSN != nil {
		return *m.DeviceSN
	}
	return ""
}

func (m *NotehubPB) GetNoteID() string {
	if m != nil && m.NoteID != nil {
		return *m.NoteID
	}
	return ""
}

func (m *NotehubPB) GetSessionIDPrev() int64 {
	if m != nil && m.SessionIDPrev != nil {
		return *m.SessionIDPrev
	}
	return 0
}

func (m *NotehubPB) GetSessionIDNext() int64 {
	if m != nil && m.SessionIDNext != nil {
		return *m.SessionIDNext
	}
	return 0
}

func (m *NotehubPB) GetSessionIDMismatch() bool {
	if m != nil && m.SessionIDMismatch != nil {
		return *m.SessionIDMismatch
	}
	return false
}

func (m *NotehubPB) GetBytes1() int64 {
	if m != nil && m.Bytes1 != nil {
		return *m.Bytes1
	}
	return 0
}

func (m *NotehubPB) GetBytes2() int64 {
	if m != nil && m.Bytes2 != nil {
		return *m.Bytes2
	}
	return 0
}

func (m *NotehubPB) GetBytes3() int64 {
	if m != nil && m.Bytes3 != nil {
		return *m.Bytes3
	}
	return 0
}

func (m *NotehubPB) GetBytes4() int64 {
	if m != nil && m.Bytes4 != nil {
		return *m.Bytes4
	}
	return 0
}

func (m *NotehubPB) GetProductUID() string {
	if m != nil && m.ProductUID != nil {
		return *m.ProductUID
	}
	return ""
}

func (m *NotehubPB) GetUsageProvisioned() int64 {
	if m != nil && m.UsageProvisioned != nil {
		return *m.UsageProvisioned
	}
	return 0
}

func (m *NotehubPB) GetUsageRcvdBytes() uint32 {
	if m != nil && m.UsageRcvdBytes != nil {
		return *m.UsageRcvdBytes
	}
	return 0
}

func (m *NotehubPB) GetUsageSentBytes() uint32 {
	if m != nil && m.UsageSentBytes != nil {
		return *m.UsageSentBytes
	}
	return 0
}

func (m *NotehubPB) GetUsageTCPSessions() uint32 {
	if m != nil && m.UsageTCPSessions != nil {
		return *m.UsageTCPSessions
	}
	return 0
}

func (m *NotehubPB) GetUsageTLSSessions() uint32 {
	if m != nil && m.UsageTLSSessions != nil {
		return *m.UsageTLSSessions
	}
	return 0
}

func (m *NotehubPB) GetUsageRcvdNotes() uint32 {
	if m != nil && m.UsageRcvdNotes != nil {
		return *m.UsageRcvdNotes
	}
	return 0
}

func (m *NotehubPB) GetUsageSentNotes() uint32 {
	if m != nil && m.UsageSentNotes != nil {
		return *m.UsageSentNotes
	}
	return 0
}

func (m *NotehubPB) GetCellID() string {
	if m != nil && m.CellID != nil {
		return *m.CellID
	}
	return ""
}

func (m *NotehubPB) GetNotificationSession() bool {
	if m != nil && m.NotificationSession != nil {
		return *m.NotificationSession
	}
	return false
}

func (m *NotehubPB) GetVoltage100() int32 {
	if m != nil && m.Voltage100 != nil {
		return *m.Voltage100
	}
	return 0
}

func (m *NotehubPB) GetTemp100() int32 {
	if m != nil && m.Temp100 != nil {
		return *m.Temp100
	}
	return 0
}

func (m *NotehubPB) GetContinuousSession() bool {
	if m != nil && m.ContinuousSession != nil {
		return *m.ContinuousSession
	}
	return false
}

func (m *NotehubPB) GetMotionSecs() int64 {
	if m != nil && m.MotionSecs != nil {
		return *m.MotionSecs
	}
	return 0
}

func (m *NotehubPB) GetMotionOrientation() string {
	if m != nil && m.MotionOrientation != nil {
		return *m.MotionOrientation
	}
	return ""
}

func init() {
	proto.RegisterType((*NotehubPB)(nil), "notelib.NotehubPB")
}

func init() { proto.RegisterFile("notehub.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xed, 0x4e, 0xdb, 0x4c,
	0x10, 0x85, 0x95, 0x97, 0x97, 0x8f, 0x2c, 0x0d, 0x85, 0x85, 0xd2, 0x29, 0xa5, 0xd4, 0xa5, 0x94,
	0x46, 0x55, 0x55, 0xf1, 0x75, 0x05, 0xc4, 0x54, 0x89, 0x54, 0xd2, 0x28, 0x0e, 0xfc, 0x77, 0x9c,
	0x01, 0x56, 0x35, 0xbb, 0x91, 0x77, 0x1d, 0xc1, 0x45, 0xf7, 0x1e, 0xaa, 0xd9, 0x75, 0x6c, 0xc7,
	0xae, 0xd4, 0x9f, 0xe7, 0x39, 0x47, 0x33, 0x63, 0xcf, 0xd8, 0xac, 0x25, 0x95, 0xc1, 0x87, 0x74,
	0xfc, 0x6d, 0x9a, 0x28, 0xa3, 0xf8, 0x2a, 0xc9, 0x58, 0x8c, 0x0f, 0x7f, 0x33, 0xd6, 0xec, 0x3b,
	0x6b, 0x70, 0xc9, 0x81, 0xad, 0xde, 0x62, 0xa2, 0x85, 0x92, 0xd0, 0xf0, 0x1a, 0xed, 0xa5, 0xe1,
	0x5c, 0x72, 0x8f, 0xad, 0x5f, 0xa3, 0xd6, 0xe1, 0x3d, 0x8e, 0x9e, 0xa7, 0x08, 0xff, 0x79, 0x8d,
	0x76, 0x73, 0x58, 0x46, 0x7c, 0x87, 0x2d, 0x5f, 0x25, 0x89, 0x4a, 0x60, 0xc9, 0x7a, 0x4e, 0xf0,
	0x7d, 0xd6, 0xf4, 0x71, 0x26, 0x22, 0xbc, 0xe9, 0xf9, 0xf0, 0xbf, 0x75, 0x0a, 0xc0, 0xbf, 0xb0,
	0x4d, 0x27, 0xae, 0xe4, 0x64, 0xaa, 0x84, 0x34, 0x3d, 0x1f, 0x96, 0x6d, 0xa8, 0xc6, 0xa9, 0x52,
	0x37, 0x1d, 0x8f, 0xc4, 0x23, 0xf6, 0x35, 0xac, 0xd8, 0xe9, 0x0a, 0xc0, 0x8f, 0x58, 0xab, 0x9b,
	0x8e, 0x4b, 0x65, 0x56, 0x6d, 0x99, 0x45, 0x48, 0xfd, 0xba, 0xe9, 0x38, 0x40, 0x4d, 0xcf, 0x34,
	0x12, 0xd1, 0x2f, 0x34, 0xb0, 0xe6, 0xfa, 0x55, 0x39, 0xff, 0xca, 0xb6, 0x0a, 0xd6, 0x0d, 0xe5,
	0x24, 0xc6, 0x04, 0x9a, 0x36, 0x5c, 0x37, 0xf8, 0x77, 0x76, 0x50, 0xad, 0x70, 0xf5, 0x34, 0x15,
	0x09, 0x6a, 0x1a, 0x30, 0xc0, 0x08, 0x98, 0x1d, 0xf9, 0x1f, 0x29, 0x7e, 0xc0, 0x18, 0xad, 0xe3,
	0x4e, 0xc4, 0xd8, 0xf3, 0x61, 0xdd, 0xb6, 0x2b, 0x11, 0xda, 0x43, 0xa1, 0x34, 0xbc, 0x70, 0x7b,
	0x28, 0x21, 0xda, 0x43, 0x20, 0x64, 0x84, 0xd0, 0xb2, 0x0d, 0x9d, 0x20, 0x7a, 0x23, 0x8d, 0x88,
	0x61, 0xc3, 0x51, 0x2b, 0xa8, 0xdb, 0x75, 0xf8, 0xd4, 0x79, 0x08, 0xe5, 0x3d, 0x6a, 0x78, 0x69,
	0xad, 0x12, 0xe1, 0x7b, 0x6c, 0xcd, 0xed, 0x21, 0xe8, 0xc3, 0xa6, 0x6d, 0x95, 0x6b, 0xbe, 0xcb,
	0x56, 0xa8, 0x6d, 0xcf, 0x87, 0x2d, 0xeb, 0x64, 0x8a, 0x36, 0x91, 0x3d, 0x60, 0xcf, 0x1f, 0x24,
	0x38, 0x03, 0x6e, 0xcb, 0x2e, 0xc2, 0x85, 0x54, 0x1f, 0x9f, 0x0c, 0x6c, 0x57, 0x52, 0x04, 0x69,
	0x07, 0x39, 0xb8, 0x16, 0xfa, 0x31, 0x34, 0xd1, 0x03, 0xec, 0x78, 0x8d, 0xf6, 0xda, 0xb0, 0x6e,
	0xd0, 0x44, 0x97, 0xcf, 0x06, 0xf5, 0x29, 0xbc, 0xb2, 0xc5, 0x32, 0x95, 0xf3, 0x33, 0xd8, 0x2d,
	0xf1, 0xb3, 0x9c, 0x9f, 0xc3, 0xeb, 0x12, 0x3f, 0xcf, 0xf9, 0x05, 0x40, 0x89, 0x5f, 0xd0, 0xdb,
	0x1a, 0x24, 0x6a, 0x92, 0x46, 0x86, 0x8e, 0xf9, 0x8d, 0xdb, 0x4d, 0x41, 0xe8, 0xba, 0x6e, 0xe8,
	0x73, 0x18, 0x24, 0x6a, 0x26, 0x68, 0x36, 0x9c, 0xc0, 0x9e, 0xad, 0x50, 0xe3, 0xfc, 0x98, 0x6d,
	0x58, 0x36, 0x8c, 0x66, 0x13, 0x5b, 0x1e, 0xde, 0x7a, 0x8d, 0x76, 0x6b, 0x58, 0xa1, 0x79, 0x2e,
	0x40, 0x69, 0x5c, 0x6e, 0xbf, 0x94, 0xcb, 0x69, 0xde, 0x7b, 0xd4, 0x19, 0x64, 0x2f, 0x46, 0xc3,
	0x3b, 0x9b, 0xac, 0xf1, 0x22, 0xfb, 0x23, 0xc8, 0xb3, 0x07, 0xe5, 0x6c, 0xc1, 0x17, 0xe6, 0xa4,
	0x05, 0x6b, 0x78, 0x5f, 0x99, 0xd3, 0xd2, 0x85, 0x39, 0x5d, 0xce, 0xab, 0xcc, 0xe9, 0x72, 0xbb,
	0x6c, 0xa5, 0x83, 0x71, 0xdc, 0xf3, 0xe1, 0x83, 0xbb, 0x1a, 0xa7, 0xf8, 0x09, 0xdb, 0xee, 0x2b,
	0x23, 0xee, 0x44, 0x14, 0x1a, 0xa1, 0x64, 0xd6, 0x1f, 0x0e, 0xed, 0xae, 0xff, 0x66, 0xd1, 0x36,
	0x6e, 0x55, 0x6c, 0xc2, 0x7b, 0x3c, 0x3d, 0x39, 0x81, 0x8f, 0x5e, 0xa3, 0xbd, 0x3c, 0x2c, 0x11,
	0xfa, 0x97, 0x8d, 0xf0, 0x71, 0x4a, 0xe6, 0x91, 0x35, 0xe7, 0x92, 0xae, 0xaa, 0xa3, 0xa4, 0x11,
	0x32, 0x55, 0xa9, 0x9e, 0x77, 0xfa, 0xe4, 0xae, 0xaa, 0x66, 0xd8, 0x6f, 0x44, 0xb9, 0xc6, 0x91,
	0x86, 0xe3, 0xec, 0x1b, 0xc9, 0x09, 0x55, 0x73, 0xea, 0x67, 0x22, 0x50, 0x1a, 0x3b, 0x23, 0x7c,
	0x76, 0xff, 0x89, 0x9a, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x4a, 0x20, 0x61, 0x88, 0x05,
	0x00, 0x00,
}
