# The Notecard supports wildcard domain names, the extreme case being that it will accept a connection
# to any server that has "*" as the subject in its certificate.
# Note that the key generated by this command is referenced only in tcps.go
openssl req -new -newkey rsa:2048 -x509 -sha256 -days 10000 -nodes -subj "/CN=*" -out hub.crt -keyout hub.key
# If you'd like to look at the key, use:
#    openssl x509 -inform PEM -in hub.crt -text

