if [ "$1" == "" ]; then
	echo "Before running your server with your notehub domain name, you must"
	echo "make a TLS key/cert for it.  If you run your server with this shell"
	echo "script, a self-signed cert will be created for you."
	echo ""
    echo "hub.sh your.notehub.domain.name.io"
	echo ""
	exit 0
fi
set -x

# Create the security directory if it doesn't exist.  Note that this script creates keys
# in this subfolder.  See keyDirectory() in main.go
mkdir -p ~/note/keys;
   
# Make a certificate with your domain name
# Note that the key generated by this command is referenced only in tcps.go
openssl req -new -newkey rsa:2048 -x509 -sha256 -days 10000 -nodes -out ~/note/keys/hub.crt -keyout ~/note/keys/hub.key \
    -subj "/CN=$1" \
    -reqexts SAN \
    -extensions SAN \
    -config <(cat /etc/ssl/openssl.cnf \
              <(printf "[SAN]\nsubjectAltName=DNS:$1"))

# Use the self-signed certificate also as the root CA, in case the device is using bidirectional auth.
# Note that the key generated by this command is referenced only in discover.go
cp ~/note/keys/hub.crt ~/note/keys/root.crt

# If you'd like to see the request to enable bidirectional auth on the notecard, see the scripts
# in the tls directory.

# Run the notehub
./hub $1
